### ISSUE TITLE
关于简历状态

### ISSUE THREAD

**Issue by shuangjie** [hzlzh/Tencent-Recruitment#1]

**Comment by hzlzh** [comment]
这里怎么了，有什么疑问？

**Comment by shuangjie** [comment]
没有，不好意思啊黄师兄，之前是想问简历状态，没消息，上github找拓展想起这个issue，原来只能close哈

**Comment by hzlzh** [comment]
没事，有任何问题可以找我咨询，QQ qiqisanliubaqi 也可以
